BACKUP DATABASE PRINCIPAL
TO DISK = 'C:\TEMP\BACKUPS\ORIGEM\PRINCIPAL.BAK'
WITH INIT, COMPRESSION;

EXEC sp_configure 'xp_cmdshell', 1;

exec xp_cmdshell 'COPY C:\TEMP\BACKUPS\ORIGEM\PRINCIPAL.BAK C:\TEMP\BACKUPS\DESTINO\PRINCIPAL.BAK'

RESTORE DATABASE SECUNDARIO
FROM DISK = 'C:\TEMP\BACKUPS\DESTINO\PRINCIPAL.BACK'
WITH STANDBY = 'C:\TEMP\SECUNDARIO\TRN\SECUNDARIO.TRN'
, MOVE 'PRINCIPAL' TO 'C:\TEMP\SECUNDARIO\MDF\SECUNDARIO_DATA.MDF'
, MOVE 'PRINCIPAL_LOG' TO 'C:\TEMP\SECUNDARIO\LDF\SECUNDARIO_LOG.LDF'
, REPLACE



exec xp_cmdshell 'COPY C:\TEMP\BACKUPS\ORIGEM\PRINCIPAL.BAK \\192.168.0.9\c$\TEMP2\BACKUPS\DESTINO\PRINCIPAL.BAK'
--e:\'




USE master;  
GO  
EXEC sp_configure 'show advanced option'





kill 54